#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:30:00
#SBATCH --output=./results/slurm_logs/slurm_output_install_requirements_%A.out

module purge
module load 2023
module load Python/3.11.3-GCCcore-12.3.0

cd $HOME/FACT_Group_19/
python -m venv venv
source ./venv/bin/activate
pip install -r requirements.txt
./utils/fix.sh
