#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=TrainDebug
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:30:00
#SBATCH --output=./results/slurm_logs/slurm_output_train_debug_%A.out

module purge
module load 2023
module load Python/3.11.3-GCCcore-12.3.0

# Store cache in scratch for read write speed.
export HF_DATASETS_CACHE="/scratch-local/scur1035"
cd $HOME/FACT_Group_19/
source ./venv/bin/activate
./run.sh train --batch-size=256
